/**
 * Bessel J/Y, Airy Ai/Bi, lgamma — AssemblyScript parity port.
 *
 * Mirrors the algorithms in:
 *   wasm-rust/crates/mathts-wasm/src/special/functions.rs  (Bessel/lgamma scalars)
 *   wasm-rust/crates/mathts-wasm/src/bessel.rs             (array kernels)
 *   wasm-rust/crates/mathts-wasm/src/special/functions.rs  (Airy scalars)
 *
 * All exported functions accept / return Float64Array and use the same
 * typed-array calling convention as the other AS kernels (tridiag.ts, poly.ts).
 *
 * Bessel J0/J1/Y0/Y1: ascending series for |x| <= 13, Hankel asymptotic
 *   above; Jn via Miller backward / forward recurrence, Yn via forward
 *   recurrence. Validated to <1e-9 vs mpmath (tests/diff-special.test.mjs).
 * Airy Ai/Bi: convergent series for |x| <= 5, asymptotic (with in-loop
 *   generated u_k coefficients) beyond. Validated to <1e-9 vs mpmath.
 *
 * Slice 4.9 — companion to Slice 3.10c-1.
 * Slice 5.8 — adds lgamma array kernel.
 */

// ===========================================================================
// Log-gamma function (Slice 5.8)
//
// Lanczos approximation: g = 7, 9 coefficients.
// Handles x ≤ 0 (non-positive integers) → +∞.
// Negative non-integer x: reflection formula  lgamma(x) = ln(π/|sin(πx)|) − lgamma(1−x).
//
// Reference: Numerical Recipes §6.1; matches Rust implementation in
//   wasm-rust/crates/mathts-wasm/src/special/functions.rs :: lgamma.
// ===========================================================================

const _LGAMMA_G: f64 = 7.0;
const _LGAMMA_C0: f64 = 0.99999999999980993;
const _LGAMMA_C1: f64 = 676.5203681218851;
const _LGAMMA_C2: f64 = -1259.1392167224028;
const _LGAMMA_C3: f64 = 771.32342877765313;
const _LGAMMA_C4: f64 = -176.61502916214059;
const _LGAMMA_C5: f64 = 12.507343278686905;
const _LGAMMA_C6: f64 = -0.13857109526572012;
const _LGAMMA_C7: f64 = 9.9843695780195716e-6;
const _LGAMMA_C8: f64 = 1.5056327351493116e-7;

function _lgamma(x: f64): f64 {
  // Poles at 0 and negative integers
  if (x <= 0.0 && x == Math.floor(x)) return Infinity;
  if (x < 0.5) {
    // Reflection: lgamma(x) = ln(π/|sin(πx)|) − lgamma(1−x)
    const sinPiX: f64 = Math.abs(Math.sin(Math.PI * x));
    if (sinPiX == 0.0) return Infinity;
    return Math.log(Math.PI / sinPiX) - _lgamma(1.0 - x);
  }
  const xm1: f64 = x - 1.0;
  let a: f64 =
    _LGAMMA_C0 +
    _LGAMMA_C1 / (xm1 + 1.0) +
    _LGAMMA_C2 / (xm1 + 2.0) +
    _LGAMMA_C3 / (xm1 + 3.0) +
    _LGAMMA_C4 / (xm1 + 4.0) +
    _LGAMMA_C5 / (xm1 + 5.0) +
    _LGAMMA_C6 / (xm1 + 6.0) +
    _LGAMMA_C7 / (xm1 + 7.0) +
    _LGAMMA_C8 / (xm1 + 8.0);
  const t: f64 = xm1 + _LGAMMA_G + 0.5;
  return 0.5 * Math.log(2.0 * Math.PI) + (xm1 + 0.5) * Math.log(t) - t + Math.log(a);
}

// ===========================================================================
// Array export — lgamma (Slice 5.8)
// ===========================================================================

/** Apply lgamma(x) element-wise.  Poles → +∞. */
export function lgamma_f64(xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _lgamma(xs[i]);
  return out;
}

// ---------------------------------------------------------------------------
// Bessel J0/J1/Y0/Y1 — ascending series (small x) + Hankel asymptotic (large x).
//
// Both regimes use coefficients generated by in-loop recurrences (no magic
// tables), so the only accuracy limits are f64 cancellation (series) and
// optimal asymptotic truncation. Replaces the legacy NR §6.5/6.8 rational
// approximations (~1e-7 for J, ~1e-4 for Y) with ~f64-accurate values.
// ---------------------------------------------------------------------------

// Euler–Mascheroni constant — for the Y ascending series.
const _EULER_GAMMA: f64 = 0.5772156649015328606;
const _TWO_OVER_PI: f64 = 0.63661977236758134308;
const _ONE_OVER_PI: f64 = 0.31830988618379067154;
// |x| at or below this uses the convergent ascending series; above it, the
// Hankel asymptotic. 13 keeps both sides at f64 accuracy across the crossover.
const _BESSEL_SERIES_MAX: f64 = 13.0;

// Hankel asymptotic expansion shared by J_nu and Y_nu (nu = 0 or 1), large x:
//   J_nu ~ sqrt(2/(pi x)) [P cos(chi) - Q sin(chi)]
//   Y_nu ~ sqrt(2/(pi x)) [P sin(chi) + Q cos(chi)],  chi = x - (nu/2 + 1/4) pi
// P = sum_j (-1)^j a_{2j}/x^{2j},  Q = sum_j (-1)^j a_{2j+1}/x^{2j+1},
//   a_0 = 1, a_k = a_{k-1} (4 nu^2 - (2k-1)^2)/(8k)   (Abramowitz & Stegun 9.2.10).
// Truncated at the smallest term (optimal asymptotic truncation).
function _besselHankel(nu: f64, x: f64, wantY: bool): f64 {
  const mu: f64 = 4.0 * nu * nu;
  let P: f64 = 1.0;
  let Q: f64 = 0.0;
  let a: f64 = 1.0; // a_0
  let xk: f64 = 1.0; // x^k
  let prevMag: f64 = Infinity;
  for (let k: i32 = 1; k <= 40; k++) {
    const twokm1: f64 = <f64>(2 * k - 1);
    a = (a * (mu - twokm1 * twokm1)) / (8.0 * <f64>k);
    xk *= x;
    const t: f64 = a / xk;
    const mag: f64 = Math.abs(t);
    if (mag > prevMag) break; // past optimal truncation — terms now diverge
    prevMag = mag;
    const m4: i32 = k & 3;
    const s: f64 = m4 == 1 || m4 == 0 ? 1.0 : -1.0; // (-1)^floor(k/2)
    if ((k & 1) == 1) Q += s * t;
    else P += s * t;
  }
  const chi: f64 = x - (nu * 0.5 + 0.25) * Math.PI;
  const amp: f64 = Math.sqrt(2.0 / (Math.PI * x));
  return wantY
    ? amp * (P * Math.sin(chi) + Q * Math.cos(chi))
    : amp * (P * Math.cos(chi) - Q * Math.sin(chi));
}

// J0 = sum_{k>=0} (-1)^k (x^2/4)^k/(k!)^2.
function _besselJ0Series(x: f64): f64 {
  const z: f64 = -0.25 * x * x;
  let term: f64 = 1.0;
  let sum: f64 = 1.0;
  for (let k: i32 = 1; k <= 80; k++) {
    const kf: f64 = <f64>k;
    term *= z / (kf * kf);
    sum += term;
    if (Math.abs(term) <= Math.abs(sum) * 1e-17) break;
  }
  return sum;
}

// J1 = (x/2) sum_{k>=0} (-1)^k (x^2/4)^k/(k!(k+1)!).
function _besselJ1Series(x: f64): f64 {
  const z: f64 = -0.25 * x * x;
  let term: f64 = 1.0; // k=0
  let sum: f64 = 1.0;
  for (let k: i32 = 1; k <= 80; k++) {
    const kf: f64 = <f64>k;
    term *= z / (kf * (kf + 1.0));
    sum += term;
    if (Math.abs(term) <= Math.abs(sum) * 1e-17) break;
  }
  return 0.5 * x * sum;
}

// Y0 = (2/pi)[ (ln(x/2)+gamma) J0 + sum_{k>=1} (-1)^{k+1} H_k (x^2/4)^k/(k!)^2 ]
//   (Abramowitz & Stegun 9.1.13).
function _besselY0Series(x: f64): f64 {
  const z: f64 = 0.25 * x * x;
  let u: f64 = 1.0; // (x^2/4)^k/(k!)^2, k=0
  let h: f64 = 0.0; // H_0
  let s: f64 = 0.0;
  let sign: f64 = 1.0; // (-1)^{k+1}, +1 at k=1
  for (let k: i32 = 1; k <= 80; k++) {
    const kf: f64 = <f64>k;
    u *= z / (kf * kf);
    h += 1.0 / kf;
    const d: f64 = sign * h * u;
    s += d;
    sign = -sign;
    if (k > 2 && Math.abs(d) <= Math.abs(s) * 1e-17) break;
  }
  return _TWO_OVER_PI * ((Math.log(0.5 * x) + _EULER_GAMMA) * _besselJ0Series(x) + s);
}

// Y1 = (2/pi)[ln(x/2)+gamma] J1 - 2/(pi x)
//      - (1/pi) sum_{k>=0} (-1)^k (H_k + H_{k+1}) (x/2)^{2k+1}/(k!(k+1)!)
//   (Abramowitz & Stegun 9.1.11).
function _besselY1Series(x: f64): f64 {
  const z: f64 = -0.25 * x * x;
  let v: f64 = 0.5 * x; // (x/2)^{2k+1}/(k!(k+1)!), k=0
  let hk: f64 = 0.0; // H_0
  let hk1: f64 = 1.0; // H_1
  let s: f64 = (hk + hk1) * v; // k=0
  for (let k: i32 = 1; k <= 80; k++) {
    const kf: f64 = <f64>k;
    v *= z / (kf * (kf + 1.0)); // (-1)^k carried by z<0
    hk += 1.0 / kf;
    hk1 += 1.0 / (kf + 1.0);
    const d: f64 = (hk + hk1) * v;
    s += d;
    if (k > 2 && Math.abs(d) <= Math.abs(s) * 1e-17) break;
  }
  return _TWO_OVER_PI * (Math.log(0.5 * x) + _EULER_GAMMA) * _besselJ1Series(x)
    - _TWO_OVER_PI / x
    - _ONE_OVER_PI * s;
}

// ---------------------------------------------------------------------------
// Bessel J0 scalar
// ---------------------------------------------------------------------------

function _besselJ0(x: f64): f64 {
  const ax: f64 = Math.abs(x);
  return ax <= _BESSEL_SERIES_MAX ? _besselJ0Series(ax) : _besselHankel(0.0, ax, false);
}

// ---------------------------------------------------------------------------
// Bessel J1 scalar
// ---------------------------------------------------------------------------

function _besselJ1(x: f64): f64 {
  const sign: f64 = x < 0.0 ? -1.0 : 1.0; // J1 is odd
  const ax: f64 = Math.abs(x);
  const val: f64 =
    ax <= _BESSEL_SERIES_MAX ? _besselJ1Series(ax) : _besselHankel(1.0, ax, false);
  return sign * val;
}

// ---------------------------------------------------------------------------
// Bessel Y0 scalar (x > 0)
// ---------------------------------------------------------------------------

function _besselY0(x: f64): f64 {
  if (x <= 0.0) return NaN;
  return x <= _BESSEL_SERIES_MAX ? _besselY0Series(x) : _besselHankel(0.0, x, true);
}

// ---------------------------------------------------------------------------
// Bessel Y1 scalar (x > 0)
// ---------------------------------------------------------------------------

function _besselY1(x: f64): f64 {
  if (x <= 0.0) return NaN;
  return x <= _BESSEL_SERIES_MAX ? _besselY1Series(x) : _besselHankel(1.0, x, true);
}

// ---------------------------------------------------------------------------
// Bessel Jn scalar (general integer order, forward/backward recurrence)
// ---------------------------------------------------------------------------

function _besselJn(n: i32, x: f64): f64 {
  const ni: i32 = n < 0 ? -n : n;
  const sign: f64 = n < 0 && ni % 2 != 0 ? -1.0 : 1.0;
  if (ni == 0) return sign * _besselJ0(x);
  if (ni == 1) return sign * _besselJ1(x);
  if (Math.abs(x) < 1e-15) return 0.0;
  // Upward recurrence is stable only when x > n; otherwise it amplifies
  // round-off (J_n decays in n for n > x). Use Miller's backward recurrence
  // in that regime.
  if (Math.abs(x) > <f64>ni) {
    // Forward recurrence
    let jPrev: f64 = _besselJ0(x);
    let jCurr: f64 = _besselJ1(x);
    for (let k: i32 = 1; k < ni; k++) {
      const jNext: f64 = (2.0 * <f64>k / x) * jCurr - jPrev;
      jPrev = jCurr;
      jCurr = jNext;
    }
    return sign * jCurr;
  }
  // Miller backward recurrence
  const isqrt: i32 = <i32>Math.sqrt(40.0 * <f64>ni);
  const extra: i32 = isqrt < 10 ? 10 : isqrt;
  const nStart: i32 = ni + 2 * extra;
  let jNext: f64 = 0.0;
  let jCurr: f64 = 1.0;
  let resultVal: f64 = 0.0;
  let sum: f64 = 0.0;
  for (let k: i32 = nStart; k >= 0; k--) {
    const jPrev: f64 = (2.0 * <f64>(k + 1) / x) * jCurr - jNext;
    jNext = jCurr;
    jCurr = jPrev;
    // After the assignments jCurr = J_k and jNext = J_{k+1}; capture J_ni.
    if (k == ni) resultVal = jCurr;
    if (k % 2 == 0) sum += jCurr;
  }
  sum = 2.0 * sum - jCurr;
  return sign * (resultVal / sum);
}

// ---------------------------------------------------------------------------
// Bessel Yn scalar (general integer order, forward recurrence; x > 0)
// ---------------------------------------------------------------------------

function _besselYn(n: i32, x: f64): f64 {
  if (x <= 0.0) return NaN;
  const ni: i32 = n < 0 ? -n : n;
  const sign: f64 = n < 0 && ni % 2 != 0 ? -1.0 : 1.0;
  if (ni == 0) return sign * _besselY0(x);
  if (ni == 1) return sign * _besselY1(x);
  let yPrev: f64 = _besselY0(x);
  let yCurr: f64 = _besselY1(x);
  for (let k: i32 = 1; k < ni; k++) {
    const yNext: f64 = (2.0 * <f64>k / x) * yCurr - yPrev;
    yPrev = yCurr;
    yCurr = yNext;
  }
  return sign * yCurr;
}

// ---------------------------------------------------------------------------
// Airy scalars — power series + asymptotic expansion
//
// Algorithm follows wasm-rust/crates/mathts-wasm/src/special/functions.rs.
// c_k coefficients: c_k = Γ(3k+1/2) / (54^k · k! · Γ(k+1/2))  (DLMF §9.7.1)
//
// Ai(0) = c1 ≈ 0.35502805388781724
// −Ai'(0) = c2 ≈ 0.25881940379280680
// ---------------------------------------------------------------------------

// Asymptotic-series coefficients u_k are generated in-loop by the recurrence
//   u_0 = 1,  u_k = u_{k-1} (6k-5)(6k-3)(6k-1) / ((2k-1) · 216 · k)
// (DLMF 9.7.2). The legacy hardcoded constants had wrong u_5/u_6, capping the
// asymptotic branch at ~1e-7; generation removes that error and lets the series
// run to its optimal-truncation point.

// Ai(0)
const AI0: f64 = 0.35502805388781723926;
// −Ai′(0)
const AI_PRIME0: f64 = 0.25881940379280679841;
// |x| threshold for switching from the convergent series to the asymptotic
// expansion. At 5.0 the series still resolves Ai/Bi to <~1e-9 (cancellation
// stays bounded), while beyond it the asymptotic series is accurate.
const XBIG: f64 = 5.0;

// Next u_k from u_{k-1} via DLMF 9.7.2.
// @inline
function _airyU(uPrev: f64, k: i32): f64 {
  const kf: f64 = <f64>k;
  return (uPrev * (6.0 * kf - 5.0) * (6.0 * kf - 3.0) * (6.0 * kf - 1.0)) /
    ((2.0 * kf - 1.0) * 216.0 * kf);
}

// Large positive x. isAi: Ai(x) ~ e^{-ζ}/(2√π x^{1/4}) Σ (-1)^k u_k/ζ^k;
//                       Bi(x) ~ e^{ζ}/(√π x^{1/4}) Σ u_k/ζ^k.   (DLMF 9.7.5/9.7.7)
function _airyAsymptotePos(x: f64, isAi: bool): f64 {
  const xp: f64 = Math.pow(x, 0.25);
  const zeta: f64 = (2.0 / 3.0) * x * Math.sqrt(x);
  let u: f64 = 1.0;
  let zk: f64 = 1.0;
  let sum: f64 = 1.0;
  let prevMag: f64 = Infinity;
  for (let k: i32 = 1; k <= 40; k++) {
    u = _airyU(u, k);
    zk *= zeta;
    const t: f64 = u / zk;
    const mag: f64 = Math.abs(t);
    if (mag > prevMag) break; // optimal asymptotic truncation
    prevMag = mag;
    sum += isAi && (k & 1) == 1 ? -t : t;
  }
  const sp: f64 = Math.sqrt(Math.PI);
  return isAi ? (Math.exp(-zeta) * sum) / (2.0 * sp * xp) : (Math.exp(zeta) * sum) / (sp * xp);
}

// Large negative x (oscillatory). θ = ζ − π/4 with
//   P = Σ (-1)^j u_{2j}/ζ^{2j},  Q = Σ (-1)^j u_{2j+1}/ζ^{2j+1}:
//   Ai(-|x|) ~ (cosθ·P + sinθ·Q)/(√π |x|^{1/4})       (DLMF 9.7.9)
//   Bi(-|x|) ~ (−sinθ·P + cosθ·Q)/(√π |x|^{1/4}).      (DLMF 9.7.10)
function _airyAsymptoteNeg(x: f64, isAi: bool): f64 {
  const ax: f64 = Math.abs(x);
  const axp: f64 = Math.pow(ax, 0.25);
  const zeta: f64 = (2.0 / 3.0) * ax * Math.sqrt(ax);
  let u: f64 = 1.0;
  let zk: f64 = 1.0;
  let P: f64 = 1.0;
  let Q: f64 = 0.0;
  let prevMag: f64 = Infinity;
  for (let k: i32 = 1; k <= 40; k++) {
    u = _airyU(u, k);
    zk *= zeta;
    const t: f64 = u / zk;
    const mag: f64 = Math.abs(t);
    if (mag > prevMag) break;
    prevMag = mag;
    const m4: i32 = k & 3;
    const s: f64 = m4 == 1 || m4 == 0 ? 1.0 : -1.0; // (-1)^floor(k/2)
    if ((k & 1) == 1) Q += s * t;
    else P += s * t;
  }
  const theta: f64 = zeta - Math.PI / 4.0;
  const sp: f64 = Math.sqrt(Math.PI);
  return isAi
    ? (Math.cos(theta) * P + Math.sin(theta) * Q) / (sp * axp)
    : (-Math.sin(theta) * P + Math.cos(theta) * Q) / (sp * axp);
}

function _airyAiSeries(x: f64): f64 {
  const x3: f64 = x * x * x;
  let f: f64 = 1.0;
  let g: f64 = x;
  let fTerm: f64 = 1.0;
  let gTerm: f64 = x;
  let factF: f64 = 1.0; // (3k)!
  let factG: f64 = 1.0; // (3k+1)!
  let prodF: f64 = 1.0; // Π(3j-2)
  let prodG: f64 = 1.0; // Π(3j-1)
  for (let k: i32 = 1; k <= 30; k++) {
    const kf: f64 = <f64>k;
    factF *= (3.0 * kf - 2.0) * (3.0 * kf - 1.0) * (3.0 * kf);
    factG *= (3.0 * kf - 1.0) * (3.0 * kf) * (3.0 * kf + 1.0);
    prodF *= 3.0 * kf - 2.0;
    prodG *= 3.0 * kf - 1.0;
    fTerm *= x3;
    gTerm *= x3;
    const df: f64 = fTerm * prodF / factF;
    const dg: f64 = gTerm * prodG / factG;
    f += df;
    g += dg;
    if (Math.abs(df) < Math.abs(f) * 1e-16 && Math.abs(dg) < Math.abs(g) * 1e-16) break;
  }
  return AI0 * f - AI_PRIME0 * g;
}

function _airyBiSeries(x: f64): f64 {
  const x3: f64 = x * x * x;
  let f: f64 = 1.0;
  let g: f64 = x;
  let fTerm: f64 = 1.0;
  let gTerm: f64 = x;
  let factF: f64 = 1.0;
  let factG: f64 = 1.0;
  let prodF: f64 = 1.0;
  let prodG: f64 = 1.0;
  for (let k: i32 = 1; k <= 30; k++) {
    const kf: f64 = <f64>k;
    factF *= (3.0 * kf - 2.0) * (3.0 * kf - 1.0) * (3.0 * kf);
    factG *= (3.0 * kf - 1.0) * (3.0 * kf) * (3.0 * kf + 1.0);
    prodF *= 3.0 * kf - 2.0;
    prodG *= 3.0 * kf - 1.0;
    fTerm *= x3;
    gTerm *= x3;
    const df: f64 = fTerm * prodF / factF;
    const dg: f64 = gTerm * prodG / factG;
    f += df;
    g += dg;
    if (Math.abs(df) < Math.abs(f) * 1e-16 && Math.abs(dg) < Math.abs(g) * 1e-16) break;
  }
  return Math.sqrt(3.0) * (AI0 * f + AI_PRIME0 * g);
}

function _airyAi(x: f64): f64 {
  if (x > XBIG) return _airyAsymptotePos(x, true);
  if (x < -XBIG) return _airyAsymptoteNeg(x, true);
  return _airyAiSeries(x);
}

function _airyBi(x: f64): f64 {
  if (x > XBIG) return _airyAsymptotePos(x, false);
  if (x < -XBIG) return _airyAsymptoteNeg(x, false);
  return _airyBiSeries(x);
}

// ===========================================================================
// Array exports — Bessel
// ===========================================================================

/** Apply J0 element-wise.  Returns zero-length array if xs is empty. */
export function bessel_j0_f64(xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _besselJ0(xs[i]);
  return out;
}

/** Apply J1 element-wise. */
export function bessel_j1_f64(xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _besselJ1(xs[i]);
  return out;
}

/** Apply J_n element-wise (fixed integer order n). */
export function bessel_jn_f64(n: i32, xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _besselJn(n, xs[i]);
  return out;
}

/** Apply Y0 element-wise (NaN for x ≤ 0). */
export function bessel_y0_f64(xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _besselY0(xs[i]);
  return out;
}

/** Apply Y1 element-wise (NaN for x ≤ 0). */
export function bessel_y1_f64(xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _besselY1(xs[i]);
  return out;
}

/** Apply Y_n element-wise (fixed integer order n; NaN for x ≤ 0). */
export function bessel_yn_f64(n: i32, xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _besselYn(n, xs[i]);
  return out;
}

// ---------------------------------------------------------------------------
// General-order array exports matching the consumed Rust export names
// `bessel_j_f64` / `bessel_y_f64`. The Rust kernels take a fixed integer
// `order` (wasm-rust/.../bessel.rs: `order: i32`), so these reuse the existing
// integer-order recurrence/Hankel logic (`_besselJn` / `_besselYn`), mirroring
// the JS general-order reference in functions/src/wasm/special/wasm-bridge.ts.
// ---------------------------------------------------------------------------

/** Apply J_order(x) element-wise (fixed integer order). */
export function bessel_j_f64(order: i32, xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _besselJn(order, xs[i]);
  return out;
}

/** Apply Y_order(x) element-wise (fixed integer order; NaN for x ≤ 0). */
export function bessel_y_f64(order: i32, xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _besselYn(order, xs[i]);
  return out;
}

// ===========================================================================
// Array exports — Airy
// ===========================================================================

/** Apply Ai(x) element-wise. */
export function airy_ai_f64(xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _airyAi(xs[i]);
  return out;
}

/** Apply Bi(x) element-wise. */
export function airy_bi_f64(xs: Float64Array): Float64Array {
  const out = new Float64Array(xs.length);
  for (let i: i32 = 0; i < xs.length; i++) out[i] = _airyBi(xs[i]);
  return out;
}

// ===========================================================================
// Complete Elliptic Integrals K(m) and E(m) via AGM (Slice 5.3)
//
// K(m) = π / (2 · agm(1, √(1−m)))
//
// E(m) via Carlson-Bulirsch AGM:
//   a₀ = 1, b₀ = √(1−m), c₀ = √m
//   iterate until convergence (quadratic — ~10 steps for f64)
//   E = K · (1 − ½ · Σ 2^k · c_k²)
//
// Domain: m ∈ [0, 1).  K(1) = +∞, E(1) = 1.  m < 0 or m > 1 → NaN.
// ===========================================================================

function _ellipticK(m: f64): f64 {
  if (isNaN(m)) return NaN;
  if (m < 0.0 || m > 1.0) return NaN;
  if (m == 1.0) return Infinity;
  if (m == 0.0) return Math.PI / 2.0;
  let a: f64 = 1.0;
  let b: f64 = Math.sqrt(1.0 - m);
  for (let i: i32 = 0; i < 50; i++) {
    const aNew: f64 = (a + b) / 2.0;
    const bNew: f64 = Math.sqrt(a * b);
    if (Math.abs(aNew - bNew) < 1e-16 * aNew) {
      a = aNew;
      break;
    }
    a = aNew;
    b = bNew;
  }
  return Math.PI / (2.0 * a);
}

function _ellipticE(m: f64): f64 {
  if (isNaN(m)) return NaN;
  if (m < 0.0 || m > 1.0) return NaN;
  if (m == 0.0) return Math.PI / 2.0;
  if (m == 1.0) return 1.0;
  let a: f64 = 1.0;
  let b: f64 = Math.sqrt(1.0 - m);
  let c: f64 = Math.sqrt(m);
  let sum: f64 = c * c; // 2^0 · c₀²
  let pow2: f64 = 1.0;
  for (let i: i32 = 0; i < 50; i++) {
    const aNew: f64 = (a + b) / 2.0;
    const bNew: f64 = Math.sqrt(a * b);
    const cNew: f64 = (a - b) / 2.0;
    pow2 *= 2.0;
    sum += pow2 * cNew * cNew;
    if (Math.abs(cNew) < 1e-16 * aNew) {
      a = aNew;
      break;
    }
    a = aNew;
    b = bNew;
    c = cNew;
  }
  const k: f64 = Math.PI / (2.0 * a);
  return k * (1.0 - 0.5 * sum);
}

// ===========================================================================
// Array exports — Elliptic K / E
// ===========================================================================

/** Apply K(m) element-wise.  Domain: m ∈ [0,1).  K(1)=+∞.  Out-of-domain → NaN. */
export function elliptic_k_f64(ms: Float64Array): Float64Array {
  const out = new Float64Array(ms.length);
  for (let i: i32 = 0; i < ms.length; i++) out[i] = _ellipticK(ms[i]);
  return out;
}

/** Apply E(m) element-wise.  Domain: m ∈ [0,1].  E(1)=1.  Out-of-domain → NaN. */
export function elliptic_e_f64(ms: Float64Array): Float64Array {
  const out = new Float64Array(ms.length);
  for (let i: i32 = 0; i < ms.length; i++) out[i] = _ellipticE(ms[i]);
  return out;
}

// ===========================================================================
// Carlson Symmetric Forms — Slice 6.4
//
// Mirrors wasm-rust/crates/mathts-wasm/src/special/functions.rs :: carlson_*.
// Duplication-theorem iterative algorithm (Numerical Recipes §6.11).
// Tolerance 0.0015 per NR; ≤ 30 iterations for f64 precision.
// ===========================================================================

function _carlsonRC(x: f64, y: f64): f64 {
  // RC is RF(x, y, y) — pure duplication, no external sum accumulation.
  // Algorithm: Carlson (1995) §2, duplication theorem for RC.
  // Reference: DLMF §19.20.3 — RC(x, y) = (1/2)∫_0^∞ (t+x)^{-1/2}(t+y)^{-1} dt
  if (x < 0.0 || y <= 0.0) return NaN;
  let xx: f64 = x;
  let yy: f64 = y;
  for (let i: i32 = 0; i < 50; i++) {
    const lam: f64 = 2.0 * Math.sqrt(xx * yy) + yy;
    xx = (xx + lam) / 4.0;
    yy = (yy + lam) / 4.0;
    const ave: f64 = (xx + 2.0 * yy) / 3.0;
    const dx: f64 = (ave - xx) / ave;
    const dy: f64 = (ave - yy) / ave;
    if (Math.abs(dx) < 1e-10 && Math.abs(dy) < 1e-10) {
      // Taylor series for RC (Carlson 1995, eq. 2.7)
      const s: f64 = dx * dx * (3.0 + dx * (1.0 + dx * (0.75 + dx * (9.0 / 22.0))));
      return (1.0 + s) / Math.sqrt(ave);
    }
  }
  return 1.0 / Math.sqrt(yy);
}

function _carlsonRF(x: f64, y: f64, z: f64): f64 {
  if (x < 0.0 || y < 0.0 || z < 0.0) return NaN;
  let xx: f64 = x;
  let yy: f64 = y;
  let zz: f64 = z;
  for (let i: i32 = 0; i < 50; i++) {
    const sx: f64 = Math.sqrt(xx);
    const sy: f64 = Math.sqrt(yy);
    const sz: f64 = Math.sqrt(zz);
    const lam: f64 = sx * sy + sy * sz + sz * sx;
    xx = (xx + lam) / 4.0;
    yy = (yy + lam) / 4.0;
    zz = (zz + lam) / 4.0;
    const ave: f64 = (xx + yy + zz) / 3.0;
    const dx: f64 = (ave - xx) / ave;
    const dy: f64 = (ave - yy) / ave;
    const dz: f64 = (ave - zz) / ave;
    if (Math.abs(dx) < 1e-10 && Math.abs(dy) < 1e-10 && Math.abs(dz) < 1e-10) {
      const e2: f64 = dx * dy - dz * dz;
      const e3: f64 = dx * dy * dz;
      return (1.0 + e2 * (-0.1 + e2 * (3.0 / 44.0) - e3 * (9.0 / 52.0)) + e3 / 14.0) /
        Math.sqrt(ave);
    }
  }
  return 1.0 / Math.sqrt(zz);
}

function _carlsonRD(x: f64, y: f64, z: f64): f64 {
  if (x < 0.0 || y < 0.0 || z <= 0.0) return NaN;
  if (x == 0.0 && y == 0.0) return NaN;
  // Degenerate case: x=y=z — algorithm converges prematurely; return exact value.
  if (x == y && y == z) return Math.pow(x, -1.5);
  let xx: f64 = x;
  let yy: f64 = y;
  let zz: f64 = z;
  let sum: f64 = 0.0;
  let fac: f64 = 1.0;
  for (let i: i32 = 0; i < 50; i++) {
    const sx: f64 = Math.sqrt(xx);
    const sy: f64 = Math.sqrt(yy);
    const sz: f64 = Math.sqrt(zz);
    const lam: f64 = sx * sy + sy * sz + sz * sx;
    sum += fac / (sz * (zz + lam));
    fac /= 4.0;
    xx = (xx + lam) / 4.0;
    yy = (yy + lam) / 4.0;
    zz = (zz + lam) / 4.0;
    const ave: f64 = (xx + yy + 3.0 * zz) / 5.0;
    const dx: f64 = (ave - xx) / ave;
    const dy: f64 = (ave - yy) / ave;
    const dz: f64 = (ave - zz) / ave;
    if (Math.abs(dx) < 1e-10 && Math.abs(dy) < 1e-10 && Math.abs(dz) < 1e-10) {
      const xy: f64 = dx * dy;
      const xz: f64 = dx * dz;
      const yz: f64 = dy * dz;
      const z2: f64 = dz * dz;
      const e2: f64 = xy - xz - yz - z2;
      const e3: f64 = xy * dz + dz * (xz + yz);
      const e4: f64 = xy * z2;
      const e5: f64 = dz * z2 * dz;
      return 3.0 * sum +
        fac * (1.0 + e2 * (-3.0 / 14.0) + e3 / 6.0 + e2 * e2 * (9.0 / 88.0) +
          e4 * (-45.0 / 132.0) - e5 * (5.0 / 44.0) + e3 * e2 * (-3.0 / 44.0)) /
        (ave * ave * Math.sqrt(ave));
    }
  }
  return 3.0 * sum + fac / (zz * zz * Math.sqrt(zz));
}

function _carlsonRJ(x: f64, y: f64, z: f64, p: f64): f64 {
  if (x < 0.0 || y < 0.0 || z < 0.0 || p == 0.0) return NaN;
  let xx: f64 = x;
  let yy: f64 = y;
  let zz: f64 = z;
  let pp: f64 = p;
  let sum: f64 = 0.0;
  let fac: f64 = 1.0;
  for (let i: i32 = 0; i < 50; i++) {
    const sx: f64 = Math.sqrt(xx);
    const sy: f64 = Math.sqrt(yy);
    const sz: f64 = Math.sqrt(zz);
    const lam: f64 = sx * sy + sy * sz + sz * sx;
    const alpha: f64 = pp * (sx + sy + sz) + sx * sy * sz;
    const alpha2: f64 = alpha * alpha;
    const beta: f64 = pp * (pp + lam) * (pp + lam);
    sum += fac * _carlsonRC(alpha2, beta);
    fac /= 4.0;
    xx = (xx + lam) / 4.0;
    yy = (yy + lam) / 4.0;
    zz = (zz + lam) / 4.0;
    pp = (pp + lam) / 4.0;
    const ave: f64 = (xx + yy + zz + pp + pp) / 5.0;
    const dx: f64 = (ave - xx) / ave;
    const dy: f64 = (ave - yy) / ave;
    const dz: f64 = (ave - zz) / ave;
    const dp: f64 = (ave - pp) / ave;
    if (Math.abs(dx) < 1e-10 && Math.abs(dy) < 1e-10 &&
        Math.abs(dz) < 1e-10 && Math.abs(dp) < 1e-10) {
      const xyz: f64 = dx * dy + dy * dz + dz * dx;
      const p2: f64 = dp * dp;
      const e2: f64 = xyz - 3.0 * p2;
      const e3: f64 = dx * dy * dz + 2.0 * xyz * dp - 3.0 * p2 * dp;
      const e4: f64 = (2.0 * dx * dy * dz + xyz * dp + 3.0 * p2 * dp) * dp;
      const e5: f64 = dx * dy * dz * p2;
      return 3.0 * sum +
        fac * (1.0 + e2 * (-3.0 / 14.0) + e3 / 6.0 + e2 * e2 * (9.0 / 88.0) -
          e4 * (45.0 / 132.0) + e5 * (-5.0 / 44.0) + e3 * e2 * (-3.0 / 44.0)) /
        (ave * ave * Math.sqrt(ave));
    }
  }
  return 3.0 * sum + fac / (pp * pp * Math.sqrt(pp));
}

// ===========================================================================
// Incomplete elliptic integrals via Carlson forms (Slice 6.4)
//
// DLMF §19.25 Legendre–Carlson identities:
//   F(φ, m) = sin(φ) · RF(cos²φ, 1−m·sin²φ, 1)
//   E(φ, m) = sin(φ) · RF(c², 1−m·s², 1) − (m/3)·s³ · RD(c², 1−m·s², 1)
//   Π(n,φ,m) = sin(φ) · RF(c², 1−m·s², 1) + (n/3)·s³ · RJ(c², 1−m·s², 1, 1−n·s²)
// ===========================================================================

function _ellipticFIncomplete(phi: f64, m: f64): f64 {
  if (phi == 0.0) return 0.0;
  const s: f64 = Math.sin(phi);
  const c: f64 = Math.cos(phi);
  const s2: f64 = s * s;
  const y: f64 = 1.0 - m * s2;
  if (y < 0.0) return NaN;
  return s * _carlsonRF(c * c, y, 1.0);
}

function _ellipticEIncomplete(phi: f64, m: f64): f64 {
  if (phi == 0.0) return 0.0;
  const s: f64 = Math.sin(phi);
  const c: f64 = Math.cos(phi);
  const s2: f64 = s * s;
  const c2: f64 = c * c;
  const y: f64 = 1.0 - m * s2;
  if (y < 0.0) return NaN;
  return s * _carlsonRF(c2, y, 1.0) - (m / 3.0) * s * s2 * _carlsonRD(c2, y, 1.0);
}

function _ellipticPiIncomplete(n: f64, phi: f64, m: f64): f64 {
  if (phi == 0.0) return 0.0;
  const s: f64 = Math.sin(phi);
  const c: f64 = Math.cos(phi);
  const s2: f64 = s * s;
  const c2: f64 = c * c;
  const y: f64 = 1.0 - m * s2;
  const q: f64 = 1.0 - n * s2;
  if (y < 0.0 || q <= 0.0) return NaN;
  return s * _carlsonRF(c2, y, 1.0) + (n / 3.0) * s * s2 * _carlsonRJ(c2, y, 1.0, q);
}

// ===========================================================================
// Array exports — Carlson forms (Slice 6.4)
// Typed-array calling convention: all input arrays must have the same length.
// ===========================================================================

/** Apply RC(x, y) element-wise. */
export function carlson_rc_f64(xs: Float64Array, ys: Float64Array): Float64Array {
  const n: i32 = xs.length;
  const out = new Float64Array(n);
  for (let i: i32 = 0; i < n; i++) out[i] = _carlsonRC(xs[i], ys[i]);
  return out;
}

/** Apply RF(x, y, z) element-wise. */
export function carlson_rf_f64(xs: Float64Array, ys: Float64Array, zs: Float64Array): Float64Array {
  const n: i32 = xs.length;
  const out = new Float64Array(n);
  for (let i: i32 = 0; i < n; i++) out[i] = _carlsonRF(xs[i], ys[i], zs[i]);
  return out;
}

/** Apply RD(x, y, z) element-wise. */
export function carlson_rd_f64(xs: Float64Array, ys: Float64Array, zs: Float64Array): Float64Array {
  const n: i32 = xs.length;
  const out = new Float64Array(n);
  for (let i: i32 = 0; i < n; i++) out[i] = _carlsonRD(xs[i], ys[i], zs[i]);
  return out;
}

/** Apply RJ(x, y, z, p) element-wise. */
export function carlson_rj_f64(xs: Float64Array, ys: Float64Array, zs: Float64Array, ps: Float64Array): Float64Array {
  const n: i32 = xs.length;
  const out = new Float64Array(n);
  for (let i: i32 = 0; i < n; i++) out[i] = _carlsonRJ(xs[i], ys[i], zs[i], ps[i]);
  return out;
}

/** Apply F(φ, m) element-wise. */
export function elliptic_f_incomplete_f64(phis: Float64Array, ms: Float64Array): Float64Array {
  const n: i32 = phis.length;
  const out = new Float64Array(n);
  for (let i: i32 = 0; i < n; i++) out[i] = _ellipticFIncomplete(phis[i], ms[i]);
  return out;
}

/** Apply E(φ, m) (incomplete) element-wise. */
export function elliptic_e_incomplete_f64(phis: Float64Array, ms: Float64Array): Float64Array {
  const n: i32 = phis.length;
  const out = new Float64Array(n);
  for (let i: i32 = 0; i < n; i++) out[i] = _ellipticEIncomplete(phis[i], ms[i]);
  return out;
}

/** Apply Π(n, φ, m) element-wise. */
export function elliptic_pi_incomplete_f64(ns: Float64Array, phis: Float64Array, ms: Float64Array): Float64Array {
  const n: i32 = ns.length;
  const out = new Float64Array(n);
  for (let i: i32 = 0; i < n; i++) out[i] = _ellipticPiIncomplete(ns[i], phis[i], ms[i]);
  return out;
}
