/**
 * Shared type-only shapes for the two independent WASM loader implementations
 * (`functions/src/wasm/WasmLoader.ts` and `matrix/src/backends/WasmLoader.ts`).
 *
 * Both packages bind to the same `mathts-as.wasm` AssemblyScript binary but each
 * declares its own package-scoped subset of the exported function ABI (`WasmModule`
 * genuinely differs between the two — matrix only needs matrix-relevant exports,
 * functions needs the full breadth including signal/geometry/special-function
 * kernels — so `WasmModule` stays local to each package). `LoadingMetrics` (perf
 * timings) and `WasmManifest` (the SHA-384 integrity manifest shape) were,
 * however, byte-for-byte identical copies with no principled reason to diverge;
 * consolidated here (cross-package type-dedup pass,
 * docs/Architecture/duplicate-symbols.json).
 *
 * @module @danielsimonjr/mathts-core/types/wasm-loader
 */

/**
 * Loading performance metrics for a WASM module load/instantiate cycle.
 */
export interface LoadingMetrics {
  fileReadMs: number;
  compileMs: number;
  instantiateMs: number;
  totalMs: number;
  fromCache: boolean;
}

/**
 * SHA-384 integrity manifest: maps a `.wasm` filename to its
 * `"sha384-<base64 digest>"` value (SRI-style), as generated by
 * `tools/generate-wasm-manifest.mjs`.
 */
export interface WasmManifest {
  [fileName: string]: string;
}
